### ISSUE TITLE
Math formula from blog don't display

### ISSUE THREAD

**Issue by codec-abc** [mukul-rathi/bolt#146]
Hi,

I just arrived from your blog (with nice articles I will surely read) but found that some formulas aren't displaying properly (at least with Firefox on W10):

For example, [This page](https://mukulrathi.co.uk/create-your-own-programming-language/intro-to-type-checking/) is displayed this way

![image](https://user-images.githubusercontent.com/1208646/127356591-ccd478ec-f775-4918-8dd2-82168aac3473.png)

**Comment by mukul-rathi** [comment]
Hi, sorry about that, I'm currently trying to fix this!

**Comment by mukul-rathi** [comment]
Fixed!
