### ISSUE TITLE
make install fails on ocamlbuild even if I build it manually

### ISSUE THREAD

**Issue by differentprogramming** [mukul-rathi/bolt#149]
The error returned is:

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlbuild 0.14.1
└─
╶─ No changes have been performed
\# Run eval $(opam env) to update the current shell environment
make: *** [Makefile:15: install] Error 31

What do I have to do to get make install to run all the way through?

**Comment by differentprogramming** [comment]
I got it working with 

opam install ocamlbuild --fake

But now I'm getting type errors in the build
I'll make that a separate issue

**Comment by differentprogramming** [comment]
ocamlbuild isn't installable with opam at the moment.
I installed it manually and told opam to accept it.  But now I'm getting type errors when building.

**Comment by paulocoghi** [comment]
I'm following your progress, since I'm also interested on Bolt, a promising language which needs some help :)
